name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./meta-photo
      run: npm install

    - name: Grant execution rights for react-scripts
      working-directory: ./meta-photo
      run: chmod +x ./node_modules/.bin/react-scripts

    - name: Build frontend
      working-directory: ./meta-photo
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./meta-photo-api
      run: npm install

    - name: Build backend
      working-directory: ./meta-photo-api
      run: npm run build

    - name: Deploy to App Engine (Frontend)
      working-directory: ./meta-photo
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud app deploy --quiet

    - name: Deploy to App Engine (Backend)
      working-directory: ./meta-photo-api
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud app deploy --quiet
